name: Cleanup images
inputs:
  package:
    description: "Name of the container registry package"
    required: true
    type: string
  filters:
    description: "A newline separated list of regular expressions matching some specific tags for the container"
    required: true
    type: string
  keep_n:
    description: "How many of the most recently created and matched tags to keep"
    required: true
    type: number
  older_than:
    description: "Only remove tags at least as old as this number of days"
    required: false
    default: -1
    type: number
  token:
    required: false
    type: string
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
